# Generated by Django 5.2.8 on 2025-11-28 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('campo01', models.CharField(max_length=80)),
                ('campo02', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Biblioteca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.IntegerField()),
                ('ciudad_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('autor', models.CharField(max_length=80)),
                ('isbn', models.IntegerField()),
                ('descripcion', models.TextField(max_length=400)),
                ('biblioteca_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.biblioteca')),
                ('genero_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.genero')),
            ],
        ),
    ]
